# Inserts a blank line between shell prompts
add_newline = true

[[battery.display]]
threshold = 20
style = "bold red"

[cmd_duration]
min_time = 250
show_milliseconds = true

[git_status]
conflicted = "ğŸ³"
# up_to_date = "âœ“"
untracked = "ğŸ¤”"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ·ï¸"
deleted = "ğŸ—‘"

[memory_usage]
disabled = false
threshold = 80
symbol = "ğŸ "
format = "via $symbol [${ram_pct} RAM]($style) "
style = "bold dimmed red"
